language: node_js
node_js:
  - "8.9"

install:
  - cd '/home/travis/build/kalliope-project/kalliope-app/kalliope' && npm install

script:
  - cd '/home/travis/build/kalliope-project/kalliope-app/kalliope' && npm run test-ci